---
title: "picrust2_analysis"
author: "Madeline Krieger"
date: "2025-09-05"
output: html_document
---

Script for analyzing Picrust2 results. These were generated with the shell script shown in "Picrust2_commands.sh"


```{r 1.1_load-packages}
library("pacman")
pacman::p_load("rmarkdown", "tidyverse", "phyloseq", "knitr","kableExtra", "here", "phyloseq", "ALDEx2", "SummarizedExperiment", "Biobase", "devtools","ComplexHeatmap", "BiocGenerics", "BiocManager", "metagenomeSeq","Maaslin2", "edgeR", "lefser", "limma", "KEGGREST", "DESeq2", "ggpicrust2", "Polychrome")
``` 



# Load data
```{r}
# Load necessary data: abundance data and metadata
pathways_file <- "picrust2_pipeline_output/pathways_out/path_abun_unstrat_descrip.tsv"

metadata <- read_delim(
    "../Pediatric_cohort/Qiime2/Files_For_Phyloseq/metadata_phyloseq.tsv",
    delim = "\t",
    escape_double = FALSE,
    trim_ws = TRUE
)

metadata <- metadata %>% as.data.frame() %>% filter(Type %in% c("Plaque", "Abscess")) 

pathway_file_read <- read_delim(
    pathways_file,
    delim = "\t",
    escape_double = FALSE,
    trim_ws = TRUE
    ) %>% as.data.frame()  %>%
    dplyr::mutate(funct = paste(pathway, description, sep = "_")) %>%
    dplyr::select(-description, -pathway)%>%
    column_to_rownames(var="funct") %>%
    dplyr::select(dplyr::all_of(metadata$SampleID)) 

metadata <- metadata %>% column_to_rownames(var="SampleID")
```


# Pathway Analysis
```{r, eval=FALSE}
iterate_maaslin2_picrust2(counts_input = pathway_file_read, 
                 metadata= metadata,
                 iterative_methods = iterative_methods,
                 group = "Type",
                 qval_threshold = .25, 
                 percentage = TRUE, plot_colors = pal20)
```

```{r}
maaslin2_pathway <- Maaslin2(input_data = pathway_file_read,
                     input_metadata = metadata,
                     fixed_effects = "Type",
                     output = "test",
                     normalization = "CLR",
                     transform = "NONE")

maaslin2_pathway_res <- maaslin2_pathway$results %>% filter(qval < .05)
write_csv(maaslin2_pathway_res, "picrust2_pipeline_output/maaslin2_pathway_res.csv")
```


